version: '3'
services:
  api:
    build: ./api
    ports:
      - "9000:9000"
    environment:
      - API_KEY=Bearer aSuperSecretKey
      - API_URL=https://echo-serv.tbxnet.com/v1/secret/
      - PORT=9000

